# TOML file for question data and scoring
[questions]
  [questions.Q1]
    text = "Do you drink on more than 2 days a week?"
    points = { "Yes" = 1, "No" = 0 }

  [questions.Q2]
    text = "Do you smoke?"
    points = { "Yes" = 1, "No" = 0 }

  [questions.Q3]
    text = "Do you exercise more than 1 hour per week?"
    points = { "Yes" = 0, "No" = 1 }

# Here map question Questions to age ranges
[scoring]
  [scoring.AGE]
    "16-21" = { Q1 = 1, Q2 = 2, Q3 = 1 }
    "22-40" = { Q1 = 2, Q2 = 2, Q3 = 3 }
    "41-65" = { Q1 = 3, Q2 = 2, Q3 = 2 }
    "64+"   = { Q1 = 3, Q2 = 3, Q3 = 1 }
